# Generated by Django 4.0.1 on 2022-01-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gr', models.CharField(max_length=200)),
                ('sun', models.IntegerField(default=5)),
                ('water', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200)),
                ('buy_date', models.DateTimeField(verbose_name='Data zakupu')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green.group')),
            ],
        ),
    ]
