# Generated by Django 4.0.1 on 2022-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_user_remove_plant_buy_date_alter_group_name_gr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
